# Build settings
theme: minima # Change this to another theme if you're not using minima
plugins:
  - jekyll-feed


# Markdown settings (optional)
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-flavored markdown

# Future post settings (if you want to enable future posts)
future: true
